<template>
  <div class="customized-wrap">
    <el-row>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
    </el-row>
    <el-row>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
    </el-row>
    <el-row>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
    </el-row>
    <el-row>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
    </el-row>
    <el-row>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
    </el-row>
    <el-row>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
    </el-row>
    <el-row>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
      <el-col>
        <icon-svg></icon-svg>
        <span></span>
      </el-col>
    </el-row>
  </div>
</template>
<script>
export default {
  name: "CustomizedIcon"
};
</script>
<style lang="scss">
.customized-wrap {
}
</style>
